-- DTA-SKILLS - DDL base (SQL Server)
-- Modelo orientado a: catálogo global + bindings por coligada + execução realtime/auditoria

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

/* ============================================================
   CATÁLOGO GLOBAL
   ============================================================ */

CREATE TABLE dbo.GIA_MODEL (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NULL,
    PROVIDER            NVARCHAR(80)    NOT NULL,
    MODEL_NAME          NVARCHAR(120)   NOT NULL,
    MODEL_FAMILY        NVARCHAR(120)   NULL,
    API_BASE_URL        NVARCHAR(500)   NULL,
    API_KEY_REF         NVARCHAR(200)   NULL,
    DEFAULT_PARAMS_JSON NVARCHAR(MAX)   NULL,
    TIMEOUT_MS          INT             NULL,
    RETRY_POLICY_JSON   NVARCHAR(MAX)   NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_MODEL_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_BY          NVARCHAR(80)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_MODEL_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY          NVARCHAR(80)    NULL,
    UPDATED_AT          DATETIME2(3)    NULL,
    ROW_VERSION         ROWVERSION
);
GO

CREATE TABLE dbo.GIA_AGENT (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    UID                 NVARCHAR(120)   NOT NULL,
    NAME                NVARCHAR(180)   NOT NULL,
    DESCRIPTION         NVARCHAR(1000)  NULL,
    SYSTEM_PROMPT       NVARCHAR(MAX)   NULL,
    ORCHESTRATION_MODE  NVARCHAR(60)    NULL,
    RUNTIME_PROVIDER    NVARCHAR(80)    NULL,
    RUNTIME_CONFIG_JSON NVARCHAR(MAX)   NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_IS_ACTIVE DEFAULT(1),
    CREATED_BY          NVARCHAR(80)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY          NVARCHAR(80)    NULL,
    UPDATED_AT          DATETIME2(3)    NULL,
    ROW_VERSION         ROWVERSION,
    CONSTRAINT UQ_GIA_AGENT_UID UNIQUE (UID)
);
GO

CREATE TABLE dbo.GIA_SKILL (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME                NVARCHAR(180)   NOT NULL,
    DESCRIPTION         NVARCHAR(1000)  NULL,
    INSTRUCTIONS        NVARCHAR(MAX)   NOT NULL,
    INPUT_SCHEMA_JSON   NVARCHAR(MAX)   NULL,
    OUTPUT_SCHEMA_JSON  NVARCHAR(MAX)   NULL,
    VERSION             NVARCHAR(40)    NOT NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_SKILL_IS_ACTIVE DEFAULT(1),
    CREATED_BY          NVARCHAR(80)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_SKILL_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY          NVARCHAR(80)    NULL,
    UPDATED_AT          DATETIME2(3)    NULL,
    ROW_VERSION         ROWVERSION,
    CONSTRAINT UQ_GIA_SKILL_NAME_VERSION UNIQUE (NAME, VERSION)
);
GO

CREATE TABLE dbo.GIA_TOOL (
    ID                      BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME                    NVARCHAR(180)   NOT NULL,
    TYPE                    NVARCHAR(50)    NOT NULL,
    APPLICATION_ID          NVARCHAR(120)   NULL,
    ENDPOINT_OR_ACTION_REF  NVARCHAR(500)   NULL,
    AUTH_SCHEME             NVARCHAR(80)    NULL,
    INPUT_SCHEMA_JSON       NVARCHAR(MAX)   NULL,
    OUTPUT_SCHEMA_JSON      NVARCHAR(MAX)   NULL,
    TIMEOUT_MS              INT             NULL,
    RATE_LIMIT              INT             NULL,
    VERSION                 NVARCHAR(40)    NOT NULL,
    IS_ACTIVE               BIT             NOT NULL CONSTRAINT DF_GIA_TOOL_IS_ACTIVE DEFAULT(1),
    CREATED_BY              NVARCHAR(80)    NULL,
    CREATED_AT              DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_TOOL_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY              NVARCHAR(80)    NULL,
    UPDATED_AT              DATETIME2(3)    NULL,
    ROW_VERSION             ROWVERSION,
    CONSTRAINT UQ_GIA_TOOL_NAME_VERSION UNIQUE (NAME, VERSION)
);
GO

CREATE TABLE dbo.GIA_RULE (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME                NVARCHAR(180)   NULL,
    RULE_TYPE           NVARCHAR(80)    NOT NULL,
    STAGE               NVARCHAR(20)    NOT NULL,
    RULE_TEXT           NVARCHAR(MAX)   NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_RULE_PRIORITY DEFAULT(100),
    STOP_ON_VIOLATION   BIT             NOT NULL CONSTRAINT DF_GIA_RULE_STOP_ON_VIOLATION DEFAULT(0),
    VERSION             NVARCHAR(40)    NOT NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_RULE_IS_ACTIVE DEFAULT(1),
    CREATED_BY          NVARCHAR(80)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_RULE_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY          NVARCHAR(80)    NULL,
    UPDATED_AT          DATETIME2(3)    NULL,
    ROW_VERSION         ROWVERSION
);
GO

CREATE TABLE dbo.GIA_GUARDRAIL (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME                NVARCHAR(180)   NOT NULL,
    DESCRIPTION         NVARCHAR(1000)  NULL,
    TYPE                NVARCHAR(80)    NOT NULL,
    STAGE               NVARCHAR(20)    NOT NULL,
    POLICY_JSON         NVARCHAR(MAX)   NULL,
    ON_VIOLATION        NVARCHAR(20)    NOT NULL,
    VERSION             NVARCHAR(40)    NOT NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_GUARDRAIL_IS_ACTIVE DEFAULT(1),
    CREATED_BY          NVARCHAR(80)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_GUARDRAIL_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    UPDATED_BY          NVARCHAR(80)    NULL,
    UPDATED_AT          DATETIME2(3)    NULL,
    ROW_VERSION         ROWVERSION
);
GO

/* ============================================================
   BINDINGS POR COLIGADA/CONTEXTO
   ============================================================ */

CREATE TABLE dbo.GIA_AGENT_MODEL_BIND (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NOT NULL,
    AGENT_ID            BIGINT          NOT NULL,
    MODEL_ID            BIGINT          NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_AGENT_MODEL_BIND_PRIORITY DEFAULT(100),
    IS_DEFAULT          BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_MODEL_BIND_IS_DEFAULT DEFAULT(0),
    OVERRIDE_CONFIG_JSON NVARCHAR(MAX)  NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_MODEL_BIND_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_MODEL_BIND_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_MODEL_BIND_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID),
    CONSTRAINT FK_GIA_AGENT_MODEL_BIND_MODEL FOREIGN KEY (MODEL_ID) REFERENCES dbo.GIA_MODEL(ID),
    CONSTRAINT UQ_GIA_AGENT_MODEL_BIND UNIQUE (CODCOLIGADA, AGENT_ID, MODEL_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_SKILL_BIND (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NOT NULL,
    AGENT_ID            BIGINT          NOT NULL,
    SKILL_ID            BIGINT          NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_AGENT_SKILL_BIND_PRIORITY DEFAULT(100),
    OVERRIDE_CONFIG_JSON NVARCHAR(MAX)  NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_SKILL_BIND_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_SKILL_BIND_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_SKILL_BIND_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID),
    CONSTRAINT FK_GIA_AGENT_SKILL_BIND_SKILL FOREIGN KEY (SKILL_ID) REFERENCES dbo.GIA_SKILL(ID),
    CONSTRAINT UQ_GIA_AGENT_SKILL_BIND UNIQUE (CODCOLIGADA, AGENT_ID, SKILL_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_TOOL_BIND (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NOT NULL,
    AGENT_ID            BIGINT          NOT NULL,
    TOOL_ID             BIGINT          NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_AGENT_TOOL_BIND_PRIORITY DEFAULT(100),
    OVERRIDE_CONFIG_JSON NVARCHAR(MAX)  NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_TOOL_BIND_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_TOOL_BIND_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_TOOL_BIND_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID),
    CONSTRAINT FK_GIA_AGENT_TOOL_BIND_TOOL FOREIGN KEY (TOOL_ID) REFERENCES dbo.GIA_TOOL(ID),
    CONSTRAINT UQ_GIA_AGENT_TOOL_BIND UNIQUE (CODCOLIGADA, AGENT_ID, TOOL_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_RULE_BIND (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NOT NULL,
    AGENT_ID            BIGINT          NOT NULL,
    RULE_ID             BIGINT          NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_AGENT_RULE_BIND_PRIORITY DEFAULT(100),
    OVERRIDE_CONFIG_JSON NVARCHAR(MAX)  NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_RULE_BIND_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_RULE_BIND_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_RULE_BIND_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID),
    CONSTRAINT FK_GIA_AGENT_RULE_BIND_RULE FOREIGN KEY (RULE_ID) REFERENCES dbo.GIA_RULE(ID),
    CONSTRAINT UQ_GIA_AGENT_RULE_BIND UNIQUE (CODCOLIGADA, AGENT_ID, RULE_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_GUARDRAIL_BIND (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA         INT             NOT NULL,
    AGENT_ID            BIGINT          NOT NULL,
    GUARDRAIL_ID        BIGINT          NOT NULL,
    PRIORITY            INT             NOT NULL CONSTRAINT DF_GIA_AGENT_GUARDRAIL_BIND_PRIORITY DEFAULT(100),
    OVERRIDE_CONFIG_JSON NVARCHAR(MAX)  NULL,
    IS_ACTIVE           BIT             NOT NULL CONSTRAINT DF_GIA_AGENT_GUARDRAIL_BIND_IS_ACTIVE DEFAULT(1),
    VALID_FROM          DATETIME2(3)    NULL,
    VALID_TO            DATETIME2(3)    NULL,
    CREATED_AT          DATETIME2(3)    NOT NULL CONSTRAINT DF_GIA_AGENT_GUARDRAIL_BIND_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_GUARDRAIL_BIND_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID),
    CONSTRAINT FK_GIA_AGENT_GUARDRAIL_BIND_GUARDRAIL FOREIGN KEY (GUARDRAIL_ID) REFERENCES dbo.GIA_GUARDRAIL(ID),
    CONSTRAINT UQ_GIA_AGENT_GUARDRAIL_BIND UNIQUE (CODCOLIGADA, AGENT_ID, GUARDRAIL_ID)
);
GO

/* ============================================================
   CHAT + EXECUÇÃO + MENSAGERIA/AUDITORIA
   ============================================================ */

CREATE TABLE dbo.GIA_CHAT_SESSION (
    SESSION_ID          UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    CODCOLIGADA         INT              NOT NULL,
    USER_ID             NVARCHAR(120)    NOT NULL,
    AGENT_ID            BIGINT           NOT NULL,
    STATUS              NVARCHAR(30)     NOT NULL,
    CREATED_AT          DATETIME2(3)     NOT NULL CONSTRAINT DF_GIA_CHAT_SESSION_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    LAST_ACTIVITY_AT    DATETIME2(3)     NULL,
    CONSTRAINT FK_GIA_CHAT_SESSION_AGENT FOREIGN KEY (AGENT_ID) REFERENCES dbo.GIA_AGENT(ID)
);
GO

CREATE TABLE dbo.GIA_CHAT_MESSAGE (
    MESSAGE_ID          UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    SESSION_ID          UNIQUEIDENTIFIER NOT NULL,
    ROLE                NVARCHAR(20)     NOT NULL,
    CONTENT             NVARCHAR(MAX)    NOT NULL,
    TOKENS_IN           INT              NULL,
    TOKENS_OUT          INT              NULL,
    CREATED_AT          DATETIME2(3)     NOT NULL CONSTRAINT DF_GIA_CHAT_MESSAGE_CREATED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_CHAT_MESSAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES dbo.GIA_CHAT_SESSION(SESSION_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_EXECUTION (
    EXECUTION_ID        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    SESSION_ID          UNIQUEIDENTIFIER NOT NULL,
    MESSAGE_ID          UNIQUEIDENTIFIER NOT NULL,
    CORRELATION_ID      UNIQUEIDENTIFIER NOT NULL,
    STATE               NVARCHAR(30)     NOT NULL,
    SUBSTATE            NVARCHAR(40)     NULL,
    STARTED_AT          DATETIME2(3)     NOT NULL CONSTRAINT DF_GIA_AGENT_EXECUTION_STARTED_AT DEFAULT(SYSUTCDATETIME()),
    FINISHED_AT         DATETIME2(3)     NULL,
    LATENCY_MS          INT              NULL,
    ERROR_CODE          NVARCHAR(80)     NULL,
    ERROR_DETAIL        NVARCHAR(MAX)    NULL,
    CONSTRAINT FK_GIA_AGENT_EXECUTION_SESSION FOREIGN KEY (SESSION_ID) REFERENCES dbo.GIA_CHAT_SESSION(SESSION_ID),
    CONSTRAINT FK_GIA_AGENT_EXECUTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES dbo.GIA_CHAT_MESSAGE(MESSAGE_ID),
    CONSTRAINT UQ_GIA_AGENT_EXECUTION_CORRELATION UNIQUE (CORRELATION_ID)
);
GO

CREATE TABLE dbo.GIA_AGENT_EVENT_LOG (
    EVENT_ID            UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    EXECUTION_ID        UNIQUEIDENTIFIER NOT NULL,
    SEQUENCE            BIGINT           NOT NULL,
    EVENT_TYPE          NVARCHAR(80)     NOT NULL,
    PAYLOAD_JSON        NVARCHAR(MAX)    NULL,
    OCCURRED_AT         DATETIME2(3)     NOT NULL CONSTRAINT DF_GIA_AGENT_EVENT_LOG_OCCURRED_AT DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_GIA_AGENT_EVENT_LOG_EXECUTION FOREIGN KEY (EXECUTION_ID) REFERENCES dbo.GIA_AGENT_EXECUTION(EXECUTION_ID),
    CONSTRAINT UQ_GIA_AGENT_EVENT_LOG_EXEC_SEQ UNIQUE (EXECUTION_ID, SEQUENCE)
);
GO

CREATE TABLE dbo.GIA_OUTBOX (
    OUTBOX_ID           BIGINT IDENTITY(1,1) PRIMARY KEY,
    AGGREGATE_TYPE      NVARCHAR(60)      NOT NULL,
    AGGREGATE_ID        NVARCHAR(120)     NOT NULL,
    EVENT_TYPE          NVARCHAR(80)      NOT NULL,
    EVENT_PAYLOAD_JSON  NVARCHAR(MAX)     NOT NULL,
    STATUS              NVARCHAR(20)      NOT NULL CONSTRAINT DF_GIA_OUTBOX_STATUS DEFAULT('PENDING'),
    RETRY_COUNT         INT               NOT NULL CONSTRAINT DF_GIA_OUTBOX_RETRY_COUNT DEFAULT(0),
    AVAILABLE_AT        DATETIME2(3)      NOT NULL CONSTRAINT DF_GIA_OUTBOX_AVAILABLE_AT DEFAULT(SYSUTCDATETIME()),
    PUBLISHED_AT        DATETIME2(3)      NULL,
    LAST_ERROR          NVARCHAR(2000)    NULL,
    CREATED_AT          DATETIME2(3)      NOT NULL CONSTRAINT DF_GIA_OUTBOX_CREATED_AT DEFAULT(SYSUTCDATETIME())
);
GO

CREATE TABLE dbo.GIA_INBOX_DEDUP (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    SOURCE              NVARCHAR(100)     NOT NULL,
    EXTERNAL_ID         NVARCHAR(200)     NOT NULL,
    RECEIVED_AT         DATETIME2(3)      NOT NULL CONSTRAINT DF_GIA_INBOX_DEDUP_RECEIVED_AT DEFAULT(SYSUTCDATETIME()),
    EXPIRES_AT          DATETIME2(3)      NULL,
    CONSTRAINT UQ_GIA_INBOX_DEDUP UNIQUE (SOURCE, EXTERNAL_ID)
);
GO

/* ============================================================
   ÍNDICES RECOMENDADOS
   ============================================================ */

CREATE INDEX IX_GIA_AGENT_ACTIVE ON dbo.GIA_AGENT (IS_ACTIVE);
CREATE INDEX IX_GIA_MODEL_ACTIVE ON dbo.GIA_MODEL (IS_ACTIVE);

CREATE INDEX IX_GIA_AGENT_SKILL_BIND_LOOKUP
    ON dbo.GIA_AGENT_SKILL_BIND (CODCOLIGADA, AGENT_ID, IS_ACTIVE, PRIORITY);

CREATE INDEX IX_GIA_AGENT_TOOL_BIND_LOOKUP
    ON dbo.GIA_AGENT_TOOL_BIND (CODCOLIGADA, AGENT_ID, IS_ACTIVE, PRIORITY);

CREATE INDEX IX_GIA_AGENT_RULE_BIND_LOOKUP
    ON dbo.GIA_AGENT_RULE_BIND (CODCOLIGADA, AGENT_ID, IS_ACTIVE, PRIORITY);

CREATE INDEX IX_GIA_AGENT_GUARDRAIL_BIND_LOOKUP
    ON dbo.GIA_AGENT_GUARDRAIL_BIND (CODCOLIGADA, AGENT_ID, IS_ACTIVE, PRIORITY);

CREATE INDEX IX_GIA_CHAT_SESSION_USER_COLIGADA
    ON dbo.GIA_CHAT_SESSION (CODCOLIGADA, USER_ID, CREATED_AT DESC);

CREATE INDEX IX_GIA_CHAT_MESSAGE_SESSION_CREATED
    ON dbo.GIA_CHAT_MESSAGE (SESSION_ID, CREATED_AT);

CREATE INDEX IX_GIA_AGENT_EXECUTION_SESSION_STARTED
    ON dbo.GIA_AGENT_EXECUTION (SESSION_ID, STARTED_AT DESC);

CREATE INDEX IX_GIA_AGENT_EXECUTION_STATE
    ON dbo.GIA_AGENT_EXECUTION (STATE, STARTED_AT DESC);

CREATE INDEX IX_GIA_AGENT_EVENT_LOG_EXEC_OCCURRED
    ON dbo.GIA_AGENT_EVENT_LOG (EXECUTION_ID, OCCURRED_AT, SEQUENCE);

CREATE INDEX IX_GIA_OUTBOX_STATUS_AVAILABLE
    ON dbo.GIA_OUTBOX (STATUS, AVAILABLE_AT, OUTBOX_ID);
GO
